# baseurl = "https://example.org/"
title = "Shane Janz Graphic Design Portfolio"
theme = "hugo-creative-portfolio"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  titleImg = "/img/portfolio/title_header.png"
  titleImgAlt = "Shane Janz Graphic Design Portfolio"
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Portfolio of Shane Janz"
  copyright = "&copy;2020 Shane Janz"
  sidebarAbout = [
    "Welcome and thanks for viewing my portfolio! My name is Shane Janz. I've worked in the field of graphic design for over ten years. I've had the opportunity to work with many wonderful people during this time, and with each client I've worked it's been my goal to help their visions come to fruition, enabling them to take their business goals and aspirations to the next level. If you like what I do, feel free to reach out and get in touch with with me."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "shanej79@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

 # [[params.navlinks]]
 # name = "About"
 # url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"


  [params.social]
# facebook      = "full page or profile url in facebook"
 email         = "shanej79@gmail.com"
# twitter       = "full profile url in twitter"
 linkedin      = "https://www.linkedin.com/in/shanejanz/"
# youtube       = "full profile url in youtube"
